# Generated by Django 3.2.7 on 2025-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.CharField(blank=True, max_length=100, null=True)),
                ('feeding_type', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency_per_day', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_per_feed_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('Notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'child_diet_plan',
            },
        ),
    ]
