# Generated by Django 3.2.7 on 2025-03-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_childdiet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostnatalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tip_number', models.CharField(blank=True, max_length=100, null=True)),
                ('Tips', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'postnatal_care_tips',
            },
        ),
    ]
