# Generated by Django 3.2.7 on 2025-03-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_postnatalcare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_reps', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fitness_exercises',
            },
        ),
    ]
