# Generated by Django 3.2.7 on 2025-03-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdiet',
            name='Notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childdiet',
            name='age_months',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childdiet',
            name='feeding_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childdiet',
            name='frequency_per_day',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='childdiet',
            name='quantity_per_feed_ml',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='duration_reps',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='instructions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='postnatalcare',
            name='Tips',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='postnatalcare',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='postnatalcare',
            name='tip_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource_tbl',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource_tbl',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource_tbl',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
