# Generated by Django 3.2.7 on 2025-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_chatgroup_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, max_length=250, null=True)),
                ('vaccine_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dose_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaccination_schedule',
            },
        ),
    ]
