# Generated by Django 3.2.7 on 2025-03-27 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_vaccinationschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=250)),
                ('child_age', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.vaccinationschedule')),
            ],
            options={
                'db_table': 'vaccination_booking',
            },
        ),
    ]
