# Generated by Django 3.2.7 on 2025-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_vaccinationbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyFoodRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('preparation_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('suitable_age', models.CharField(blank=True, help_text='Suitable age range', max_length=100, null=True)),
                ('nutrition_facts', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'healthy_food_recipes',
            },
        ),
    ]
