# Generated by Django 3.2.7 on 2025-03-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_healthyfoodrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPreparedness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emergency_type', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('immediate_action', models.TextField()),
            ],
            options={
                'db_table': 'emergency_preparedness',
            },
        ),
    ]
