# Generated by Django 3.2.7 on 2025-03-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_emergencypreparedness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stories',
            },
        ),
    ]
