# Generated by Django 3.2.7 on 2025-03-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='moral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story',
            field=models.TextField(),
        ),
    ]
